version: '3'

services:
  backend:
    build: ./WakeCountyDataAnalysis/backend
    volumes:
      - ./WakeCountyDataAnalysis/backend:/app/backend
    ports:
      - 5001:5001

  frontend:
    build: 
      context: ./WakeCountyDataAnalysis/frontend

    volumes:
      - ./WakeCountyDataAnalysis/frontend:/app
    ports:
      - 8080:8080
    # environment:
    #   - NEXT_PUBLIC_API_URI=http://127.0.0.1:5001
    
