version: '3'

services:
  backend:
    build: ./WakeCountyDataAnalysis/backend
    volumes:
      - ./WakeCountyDataAnalysis/backend:/app/backend
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}


  frontend:
    build: 
      context: ./WakeCountyDataAnalysis/frontend

    volumes:
      - ./WakeCountyDataAnalysis/frontend:/app
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:${BACKEND_PORT}

   
