version: '3'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - 5001:5001
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - 8080:8080


